# Generated by Django 6.0 on 2025-12-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Severity', models.CharField(choices=[('CRITICAL', 'critical'), ('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('FIXED', 'fixed'), ('VERIFIED', 'verified'), ('CLOSED', 'closed')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
