# Generated by Django 6.0 on 2025-12-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='Severity',
            new_name='severity',
        ),
    ]
