# Generated by Django 6.0 on 2025-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_severity_issues_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('FIXED', 'fixed'), ('VERIFIED', 'verified'), ('CLOSED', 'closed')], default='OPEN', max_length=15),
        ),
    ]
