# Generated by Django 6.0 on 2025-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issues_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='OPEN', max_length=15),
        ),
    ]
