# Generated by Django 6.0 on 2025-12-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_changerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='change_requests',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='issues.issues'),
        ),
    ]
