# Generated by Django 6.0 on 2025-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_remove_changerequest_change_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='issues',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
    ]
